# Generated by Django 3.2.7 on 2021-10-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electorate',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('std_id', models.CharField(max_length=8)),
                ('pass_key', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
