# Generated by Django 3.2.7 on 2021-10-04 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_electorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electorate',
            name='pass_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
